In [5]:
import numpy as np

## 1. Create a Numpy array of 100 random numbers and find mean, median and variance.

In [56]:
arr = (np.random.randint(100, size = 100))

print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Variance: {np.var(arr)}")

Mean: 52.03
Median: 49.5
Variance: 801.2291000000001


## 2. Generate an array of integers from 1 to 100 and extract all even numbers.

arr = np.arange(0, 101, 2)
arr

## 3. Given a 2D array of sales data (rows=days, cols=products), find total sales per product.

In [24]:
arr = np.array([np.arange(1, 10), np.random.randint(1000, size=9)])
print(arr)
np.sum(arr[1], axis = 0)

[[  1   2   3   4   5   6   7   8   9]
 [492 710 578 613 688 178 495 698 746]]


np.int64(5198)

## 4. Create a 5x5 matrix of random integers and replace all values < 10 with 0

In [38]:
arr = (np.random.randint(100, size=25)).reshape((5, 5))
arr[arr < 10] = 0
arr

array([[59, 34, 82, 84, 91],
       [39, 80, 54, 32,  0],
       [41, 40, 26, 83, 61],
       [44, 33, 64, 75, 89],
       [83, 60, 75, 65,  0]], dtype=int32)

## 5. Create an array of temperatures in Celsius and convert to Farenheit using vectorization.

In [43]:
cel = np.array([34 ,54, 23, 54, 32, 6, 43, 76])

far = (5/9)*(cel+32)

print(f"Celcius: {cel}")
print(f"Farenheit: {far}")

Celcius: [34 54 23 54 32  6 43 76]
Farenheit: [36.66666667 47.77777778 30.55555556 47.77777778 35.55555556 21.11111111
 41.66666667 60.        ]


## 6. Create an 1D array and  reverse it without using a loop.

In [45]:
arr = np.random.randint(100, size=10)
print(f"{arr} \n{arr[::-1]}")

[24 23 16  9 48 46 26 62 67 18] 
[18 67 62 26 46 48  9 16 23 24]


## 7. Generate 1000 random ages(18-60) and how many are above 40

In [48]:
age = np.random.randint(18, 61, size=1000)
print(age)
print(np.sum(age > 40))

[34 24 19 31 40 41 27 21 41 26]
2


## 8. Create a 3x3 identity matrix without np.eye


In [50]:
arr = np.diag([1, 1, 1])
arr


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 9. From an array of employee salaries, find top 3 salaries.

In [53]:
salary = np.random.randint(10000, 100000, size=10)
s = np.sort(salary)[-3:]
s

array([53543, 59774, 70953], dtype=int32)