In [2]:
import numpy as np

## 1. Create a Numpy array of 100 random numbers and find mean, median and variance.

In [3]:
arr = (np.random.randint(100, size = 100))

print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Variance: {np.var(arr)}")

Mean: 57.9
Median: 62.0
Variance: 710.3300000000002


## 2. Generate an array of integers from 1 to 100 and extract all even numbers.

In [4]:
arr = np.arange(0, 101, 2)
arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

## 3. Given a 2D array of sales data (rows=days, cols=products), find total sales per product.

In [5]:
arr = np.array([np.arange(1, 10), np.random.randint(1000, size=9)])
print(arr)
np.sum(arr[1], axis = 0)

[[  1   2   3   4   5   6   7   8   9]
 [ 92 948 465 540 667 900 280 284  91]]


np.int64(4267)

## 4. Create a 5x5 matrix of random integers and replace all values < 10 with 0

In [6]:
arr = (np.random.randint(100, size=25)).reshape((5, 5))
arr[arr < 10] = 0
arr

array([[23, 20, 84, 53, 96],
       [39, 54, 79, 63, 95],
       [70, 28, 36, 36, 49],
       [27, 88, 41, 44, 76],
       [62, 61, 63, 72, 23]], dtype=int32)

## 5. Create an array of temperatures in Celsius and convert to Farenheit using vectorization.

In [7]:
cel = np.array([34 ,54, 23, 54, 32, 6, 43, 76])

far = (5/9)*(cel+32)

print(f"Celcius: {cel}")
print(f"Farenheit: {far}")

Celcius: [34 54 23 54 32  6 43 76]
Farenheit: [36.66666667 47.77777778 30.55555556 47.77777778 35.55555556 21.11111111
 41.66666667 60.        ]


## 6. Create an 1D array and  reverse it without using a loop.

In [8]:
arr = np.random.randint(100, size=10)
print(f"{arr} \n{arr[::-1]}")

[23 91 95 58 16 11 71 62 58 69] 
[69 58 62 71 11 16 58 95 91 23]


## 7. Generate 1000 random ages(18-60) and how many are above 40

In [9]:
age = np.random.randint(18, 61, size=1000)
print(age)
print(np.sum(age > 40))

[59 20 29 57 38 56 53 32 47 57 35 59 44 30 52 54 55 24 22 30 40 33 25 37
 52 54 30 40 56 39 27 47 43 55 38 55 21 40 30 53 54 26 59 26 56 55 27 41
 39 55 59 30 21 31 32 21 55 54 27 42 54 44 35 29 47 58 51 23 32 37 31 43
 27 52 24 43 20 50 59 36 28 50 41 23 55 20 36 35 52 24 39 56 27 33 48 35
 24 20 37 35 42 23 46 60 33 40 41 48 44 47 38 37 39 36 44 39 44 60 52 40
 60 60 35 23 59 39 31 53 26 54 49 20 26 55 23 50 42 38 27 32 23 39 44 28
 21 43 60 30 47 35 39 37 26 60 27 50 32 29 56 52 45 34 58 46 20 59 57 51
 49 46 52 48 21 41 57 29 55 20 44 57 41 53 53 44 44 28 42 38 31 31 24 48
 43 56 33 57 31 48 53 54 24 36 18 24 44 45 57 44 35 45 41 54 29 38 42 30
 58 25 40 20 32 18 48 41 19 35 33 40 25 60 36 51 30 37 36 60 51 36 45 53
 24 45 26 50 33 21 49 32 21 54 36 33 28 24 55 27 37 36 58 48 24 38 37 32
 26 36 23 48 35 47 37 44 56 33 27 52 37 40 60 27 21 26 22 37 18 23 49 20
 47 44 54 26 23 34 19 60 21 52 38 59 27 28 32 55 47 43 58 49 25 37 32 53
 57 42 40 41 31 38 57 28 18 18 23 28 21 18 19 26 34

## 8. Create a 3x3 identity matrix without np.eye


In [10]:
arr = np.diag([1, 1, 1])
arr


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 9. From an array of employee salaries, find top 3 salaries.

In [11]:
salary = np.random.randint(10000, 100000, size=10)
s = np.sort(salary)[-3:]
s

array([61263, 71281, 76908], dtype=int32)