In [1]:
import numpy as np

## 1. Convert a week's Celcius temperature into Farenheit

In [2]:
celWeek = (np.random.uniform(15, 40, 7))
farhenWeek = 9/5 * celWeek + 32
print(f"Celsius: {celWeek}")
print(f"Farenheit: {farhenWeek}")

Celsius: [38.15189205 31.22599116 17.98758608 39.1460337  26.17298991 25.61136964
 36.14217107]
Farenheit: [100.67340569  88.20678409  64.37765494 102.46286066  79.11138184
  78.10046535  97.05590793]


## 2. Generate 365 days temperature and extract January data

In [3]:
tempYear = (np.random.uniform(10, 40, 365))
tempYear[:32]

array([19.83893531, 31.64662999, 11.12892672, 15.4580732 , 33.84083577,
       37.23805205, 13.861038  , 23.06611845, 18.04037312, 38.8115542 ,
       39.298398  , 12.10091844, 39.44532713, 13.98230437, 23.50943868,
       11.76737897, 31.03527853, 13.50782392, 14.01719459, 30.35776428,
       34.51327276, 30.38790325, 34.87830888, 23.41518022, 28.83876407,
       21.06865835, 28.22452086, 15.70382223, 38.85631953, 12.01786998,
       23.65498299, 18.74356832])

## 3. Create hourly website traffic data for 24hrs

In [4]:
traffic = np.random.randint(10000, size= 24)
traffic

array([5186, 6202, 3560, 3935, 1305, 6073, 8803, 6799, 1025, 7253, 2062,
       9363,  116, 3299,  664, 5050, 4804, 1920, 9811, 7575, 1477, 4653,
       8027, 2635], dtype=int32)

## 4. Generate 12 Mointh rainfall dataset using linespace (50-300 mm)

In [5]:
monthRain = np.linspace(13, 100, 12)
monthRain

array([ 13.        ,  20.90909091,  28.81818182,  36.72727273,
        44.63636364,  52.54545455,  60.45454545,  68.36363636,
        76.27272727,  84.18181818,  92.09090909, 100.        ])

## 5. Store makrs of 1000 students and convert dtype into float

In [6]:
stMarks = np.random.randint(50, 100, 1000)
stMarks = stMarks.astype(np.float64)
stMarks.dtype

dtype('float64')

## 6. Create a 30 day step count dataset for a fitness tracker.

In [7]:
stepCount = np.random.randint(5000, 15000, 30)
stepCount

array([ 9385, 10645, 11133, 13655, 12422, 10032,  9997, 12811,  7427,
        5050, 14889, 11868, 11453,  9743,  7584,  7115, 13228, 12970,
       10891, 14814,  6997,  8966, 12981, 10905,  5977,  5235,  6552,
        6129, 11918,  7880], dtype=int32)

## 7. Generate a 7x24 matrix representing a full week's energy usage.

In [8]:
np.random.seed(0)
energyUsage = np.random.uniform(40, 200, [7, 24])
energyUsage

array([[127.81016063, 154.43029862, 136.44214017, 127.18130928,
        107.78476789, 143.34305809, 110.0139538 , 182.68368013,
        194.18604168, 101.35064301, 166.67600609, 124.62318716,
        130.88712978, 188.09546213,  51.36576931,  53.94068795,
         43.23494359, 173.21917529, 164.50508015, 179.20194372,
        196.57893476, 167.86537027, 113.83669796, 164.88466821],
       [ 58.92390814, 142.38736341,  62.93652599, 191.14702673,
        123.49573148, 106.3459104 ,  82.32889794, 163.87739031,
        112.98405315, 130.94943182,  43.00636807, 138.82167953,
        137.93531564, 138.7094395 , 190.99969256, 149.09124786,
         97.52126409, 109.92511261, 151.62099135,  49.63607546,
        146.68267447, 147.30205914,  73.66120977,  60.62820762],
       [ 90.46853615,  98.19372335, 131.23148327, 110.17624215,
        198.13981409,  56.32716972,  73.42028098,  65.80952286,
        144.49733207,  80.52665641, 114.60972366,  79.10809472,
         65.43513338,  57.66002259, 14

## 8. Create stock-prices for 90 days with gradual increase.

In [9]:
np.random.seed(0)
stockPrices = np.random.uniform(10, 40, 90)
stockPrices = np.cumsum(stockPrices)
stockPrices

array([  26.46440512,   57.92008611,   86.00298739,  112.34948288,
        135.05912686,  164.43595025,  187.56356659,  224.31675661,
        263.22663943,  284.72988499,  318.48163614,  344.34848373,
        371.38982056,  409.15771971,  421.28880146,  433.90268045,
        444.50923237,  479.48782774,  512.83253027,  548.93289471,
        588.29144498,  622.26620191,  646.11058277,  679.52645806,
        693.07469084,  722.27232148,  736.5729201 ,  774.91298761,
        800.56843727,  823.00829547,  840.94496383,  874.17197451,
        897.85648448,  924.90950294,  935.47319696,  964.00226187,
        992.36513355, 1020.87315346, 1059.18559581, 1089.64020479,
       1110.4254418 , 1133.53640042, 1164.46533629, 1176.27210044,
       1206.27510191, 1236.394238  , 1252.70571483, 1266.57350376,
       1286.03635429, 1306.94767741, 1334.05358053, 1357.21162593,
       1396.86284107, 1409.92418539, 1426.19048808, 1441.02977361,
       1470.62302338, 1488.22177145, 1512.21109464, 1529.54386

## 9. Create height and weight dataset for 500 people.

In [12]:
np.random.seed(0)
weight = np.random.uniform(40, 90, 500)
height = np.random.uniform(135, 175, 500)
hw = np.column_stack((height, weight))
hw

array([[147.41523304,  67.4406752 ],
       [149.92139456,  75.75946832],
       [155.99881769,  70.1381688 ],
       [165.02380092,  67.24415915],
       [148.34029863,  61.18273997],
       [171.96635066,  72.29470565],
       [169.49274187,  61.87936056],
       [136.94761184,  84.58865004],
       [145.14570097,  88.18313803],
       [152.84542051,  59.17207594],
       [139.18511555,  79.5862519 ],
       [148.93903956,  66.44474599],
       [164.60390102,  68.40222805],
       [162.22057925,  86.27983191],
       [159.89537714,  43.55180291],
       [163.42113611,  44.35646499],
       [143.19694748,  41.01091987],
       [148.66792459,  81.63099228],
       [162.04969929,  78.90783755],
       [170.16939052,  83.50060741],
       [156.74712215,  88.93091711],
       [146.30798604,  79.95792821],
       [136.20941032,  63.07396811],
       [163.41347316,  79.02645881],
       [135.31536414,  45.91372129],
       [149.90716279,  71.99605107],
       [156.22148858,  47.16766437],
 

## 10. Create a 1000x4 industrial machine sensor data

In [18]:
sensor = np.random.uniform(0, 1, [1000, 4])
print(sensor)

[[0.49619406 0.85284717 0.31949108 0.58024929]
 [0.44871517 0.30545995 0.33839224 0.28976151]
 [0.1869059  0.95149423 0.34113276 0.97151078]
 ...
 [0.81769778 0.53508496 0.06128967 0.94805466]
 [0.39389375 0.09482412 0.91460277 0.95959536]
 [0.50376572 0.60458944 0.02152642 0.63377477]]
