In [36]:
import numpy as np

## 1. Generate a 28x28 grayscale image and print shape and size.

In [37]:
mat = np.random.random(784).reshape((28, 28))
mat

array([[7.64841466e-01, 8.23872318e-01, 5.30498937e-01, 2.33921972e-04,
        4.27449106e-01, 2.03030844e-01, 4.92795978e-01, 1.53943833e-01,
        2.49848750e-02, 7.85770588e-01, 6.21117590e-01, 8.05676601e-02,
        7.71861910e-01, 3.76317268e-01, 8.17138624e-01, 9.63970205e-02,
        8.13398431e-02, 2.91158314e-01, 2.02315111e-01, 9.27777493e-01,
        8.13940743e-01, 6.23965830e-01, 8.34505713e-01, 7.21736885e-01,
        6.35909270e-01, 9.10431674e-01, 3.41114576e-01, 9.58174109e-02],
       [4.11744934e-02, 7.54539915e-01, 8.07868930e-01, 6.30956311e-01,
        8.53134658e-01, 5.90410502e-01, 4.89390712e-01, 3.90322682e-01,
        6.28972630e-01, 9.03458814e-01, 9.56500140e-01, 9.79601086e-01,
        3.84263806e-01, 7.86308890e-01, 5.44266570e-01, 4.14732183e-01,
        6.46818482e-01, 5.52122628e-01, 8.31698006e-01, 6.34496769e-01,
        5.19171146e-01, 2.79774703e-01, 8.17366176e-01, 4.04906416e-01,
        1.89123435e-01, 1.53630392e-01, 1.60244268e-01, 8.17368

## 2. Reshape a 1D array of 30 days sales into weeks (4x7 with leftover)

In [38]:
arr = np.random.random(30)*10
weeks = arr[:28].reshape((4, 7))
left = arr[28:]
arr2 = [weeks, left]
arr2

[array([[4.31998912, 3.38737474, 1.20601443, 0.31783276, 8.61598276,
         0.28946853, 7.85870821],
        [1.95754519, 4.70636317, 6.32121623, 0.56394419, 5.50764889,
         2.70272091, 2.28380249],
        [7.93337594, 6.15007524, 7.35822489, 7.01552749, 3.98902594,
         6.35447203, 0.07520928],
        [0.46840999, 8.36584105, 6.26349804, 2.3244681 , 2.74595724,
         8.03364696, 7.23625535]]),
 array([4.51571838, 0.37910837])]

## 3. Reshape 1000 students' 3 subject marks into (1000, 3)

In [39]:
marks = (np.random.uniform(50, 100, 3000)).reshape(1000, 3)
marks

array([[56.13101968, 78.48857422, 73.63736488],
       [69.44874494, 70.8909119 , 59.9887976 ],
       [98.52475779, 56.49536067, 70.47688334],
       ...,
       [63.8054188 , 50.1571122 , 75.66428465],
       [77.48004849, 53.26507095, 74.49866897],
       [75.29073858, 95.41196101, 63.45149104]])

## 4. Convert 10x10 matrix into a column vector

In [40]:
vec = np.arange(100).reshape(100, 1)
vec

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50],
       [51],
       [52],
       [53],
       [54],
       [55],
       [56],
       [57],
       [58],
       [59],
       [60],
       [61],
       [62],
       [63],
       [64],
       [65],
       [66],
       [67],
       [68],
       [69],
       [70],
       [71],
       [72],
       [73],
       [74],
       [75],
       [76],

## 5. Simulate MNIST-like data: reshape 784 into 28x28

In [41]:
mat = np.random.random(784).reshape((28, 28))
mat

array([[9.12755731e-01, 5.08292230e-01, 7.21527317e-01, 5.82691889e-01,
        9.01204048e-02, 5.89333438e-01, 9.32555622e-01, 5.21247479e-02,
        1.18229355e-01, 8.89640933e-01, 1.78209979e-01, 3.60415534e-01,
        3.48082294e-01, 5.03904299e-01, 1.61140228e-01, 2.63069519e-01,
        7.13860940e-01, 9.89600458e-02, 9.79908776e-01, 8.53974001e-01,
        6.44476762e-01, 4.60093943e-01, 4.90491367e-01, 3.18223289e-01,
        3.59473244e-01, 8.89216844e-02, 6.65198748e-01, 1.58931757e-01],
       [3.93604793e-01, 3.76996527e-01, 9.93083468e-01, 5.70991924e-01,
        8.73571822e-01, 2.94360120e-01, 3.19937838e-02, 9.05596612e-01,
        3.32049315e-01, 7.52080326e-01, 2.16248812e-01, 1.80009063e-01,
        4.34215062e-01, 8.02027592e-01, 9.03332506e-01, 4.24588568e-01,
        3.90565531e-02, 8.60851166e-01, 6.69667294e-01, 4.67157509e-01,
        4.13194455e-01, 3.04890680e-01, 4.91549602e-01, 7.80754209e-02,
        3.27081703e-01, 5.74144570e-01, 2.20289813e-01, 2.61376

## 6. Given a dataset of 100 houses (features=5), reshape to (100, 5)

In [42]:
houses = np.random.randint(10, 1000, size=500).reshape(100, 5)
houses

array([[184, 867, 307, 953, 277],
       [182, 707, 117,  74, 788],
       [198, 174, 439, 638, 205],
       [249, 125, 356, 490, 220],
       [940, 446, 870, 932, 772],
       [ 59, 247, 714, 111, 786],
       [849, 628, 107, 481, 730],
       [595, 447, 966, 300, 555],
       [682, 899, 204,  33, 169],
       [266, 300, 905, 463, 286],
       [171, 101, 542, 423, 408],
       [599, 848, 620, 803, 848],
       [411, 423, 382, 506, 684],
       [406,  90, 407, 131, 974],
       [404, 920, 724, 874, 564],
       [833, 444,  37, 549, 800],
       [533, 909, 761, 482, 109],
       [145, 912, 658, 529, 293],
       [564, 974, 306, 184, 323],
       [787, 101, 797, 354, 255],
       [852, 859, 524, 916, 513],
       [250, 292, 331, 311, 429],
       [798, 428, 503, 460, 415],
       [381, 659, 390, 765, 872],
       [886, 914, 259, 918, 468],
       [830, 722, 458, 614, 105],
       [862, 657, 626, 161,  21],
       [ 89, 759, 394, 902, 942],
       [863, 435, 360, 251, 165],
       [593, 7

## 7. Flatten a 100x100 image for ML preprocessing

In [43]:
img = np.random.uniform(0, 1, [100, 100])
img.flatten()

array([0.38028229, 0.72375845, 0.57099489, ..., 0.12349802, 0.51479979,
       0.18955821])

## 8. Add a new axis to convert (100,) into (100, 1)

In [44]:
new = np.random.randint(9, size=100)
n2 = np.expand_dims(arr, axis=0)
n2

array([[4.31998912, 3.38737474, 1.20601443, 0.31783276, 8.61598276,
        0.28946853, 7.85870821, 1.95754519, 4.70636317, 6.32121623,
        0.56394419, 5.50764889, 2.70272091, 2.28380249, 7.93337594,
        6.15007524, 7.35822489, 7.01552749, 3.98902594, 6.35447203,
        0.07520928, 0.46840999, 8.36584105, 6.26349804, 2.3244681 ,
        2.74595724, 8.03364696, 7.23625535, 4.51571838, 0.37910837]])

## 9. Rotate a 10x10 matrix using transpose (swap axes)

In [45]:
img = np.random.uniform(0, 1, [100, 100])
img.T

array([[0.59104696, 0.96137845, 0.62726838, ..., 0.09329891, 0.82675176,
        0.01632808],
       [0.53887197, 0.32107689, 0.63772035, ..., 0.15134724, 0.49415217,
        0.51541084],
       [0.4881806 , 0.85924003, 0.99715302, ..., 0.95408523, 0.28966047,
        0.92806144],
       ...,
       [0.75319065, 0.58114568, 0.71040553, ..., 0.44685719, 0.81873543,
        0.21013697],
       [0.34593069, 0.70225862, 0.00147795, ..., 0.52750797, 0.02932273,
        0.43134228],
       [0.34178227, 0.94042341, 0.19170887, ..., 0.24391092, 0.45851358,
        0.07371903]])

## 10. Combine multiple reshape operations to convert 3D video(frames x H x W) into a single 2D matrix

In [46]:
video3d = np.random.randint(5, 10, (100, 5, 5))
f, H, W = video3d.shape
neww = video3d.reshape(f, H*W, 1)
video2d = neww.squeeze()
video2d

array([[6, 8, 5, ..., 8, 8, 8],
       [9, 9, 6, ..., 8, 8, 6],
       [5, 5, 6, ..., 9, 6, 9],
       ...,
       [7, 7, 8, ..., 6, 9, 7],
       [6, 8, 8, ..., 6, 6, 7],
       [9, 6, 9, ..., 8, 7, 6]], dtype=int32)