In [2]:
import numpy as np

## 1. Extract first week's temperatures from a 30-day dataset

In [3]:
temps = np.random.randint(15, 40, 30)
temps[:7]

array([19, 23, 29, 20, 21, 24, 39], dtype=int32)

## 2. Slice monsoon (day 180-260) from 365-day rainfall dataset

In [4]:
monsoon = np.arange(365)
monsoon[180:261]

array([180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
       193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
       219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
       232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
       245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
       258, 259, 260])

## 3. Get weekends (rows 5 and 6) from 7x24 energy dataset

In [8]:
energy = np.random.uniform(40, 202, [7, 24])
energy[5:7]

array([[152.19935764, 153.37747659, 141.384396  ,  77.8344918 ,
         77.59304881,  69.84279729, 137.26136508, 116.48162474,
        169.81316326,  57.93522832, 105.10082211, 172.53668589,
        197.13738872,  62.6633288 ,  78.37630912, 102.4624979 ,
        112.28602264,  56.31056496,  65.52260481, 102.89289367,
        139.63819223,  50.18161048,  79.55153712,  72.41725461],
       [132.08451365,  96.32894975, 186.89220575,  83.70059907,
        133.4136107 ,  92.25904371, 107.72995402,  87.71063196,
         82.88298694, 148.70807926, 145.66898919, 194.35602059,
        127.39343249,  75.68804996,  77.22149389, 146.43285789,
        146.34041081, 162.07475102,  42.11541986, 134.16471956,
         46.60458191, 153.9973803 , 131.33617105,  53.3226429 ]])

## 4. Reverse a 12-month revenue array

In [14]:
rev = np.linspace(100, 1000, 12)
print(rev)
rev[::-1]

[ 100.          181.81818182  263.63636364  345.45454545  427.27272727
  509.09090909  590.90909091  672.72727273  754.54545455  836.36363636
  918.18181818 1000.        ]


array([1000.        ,  918.18181818,  836.36363636,  754.54545455,
        672.72727273,  590.90909091,  509.09090909,  427.27272727,
        345.45454545,  263.63636364,  181.81818182,  100.        ])

## 5. Extract week-2 closing prices from stock matrix

In [20]:
rev = np.linspace(100, 2000, 28).reshape(4, 7)
print(rev)
rev[1, [-1]]

[[ 100.          170.37037037  240.74074074  311.11111111  381.48148148
   451.85185185  522.22222222]
 [ 592.59259259  662.96296296  733.33333333  803.7037037   874.07407407
   944.44444444 1014.81481481]
 [1085.18518519 1155.55555556 1225.92592593 1296.2962963  1366.66666667
  1437.03703704 1507.40740741]
 [1577.77777778 1648.14814815 1718.51851852 1788.88888889 1859.25925926
  1929.62962963 2000.        ]]


array([1014.81481481])

## 6. Extract every alternate hour from traffic dataset

In [21]:
dayta = np.random.uniform(20, 100, 24)
print(dayta)
dayta[::2]

[78.68626348 57.73047168 42.48316015 68.17076574 78.62113514 21.88559864
 37.26272295 64.84389671 99.15457696 93.30787752 93.64911233 76.74633547
 71.27181113 81.08438924 93.26710159 58.8185873  71.5199761  34.55798026
 50.41160559 46.70775433 43.2450685  94.61286568 67.69766515 54.52957135]


array([78.68626348, 42.48316015, 78.62113514, 37.26272295, 99.15457696,
       93.64911233, 71.27181113, 93.26710159, 71.5199761 , 50.41160559,
       43.2450685 , 67.69766515])

## 7. Extract only humidity column from 1000x3 weather dataset

In [24]:
# temp, humidity, wind
weather = np.random.randint(0, 100, size=(1000, 3))
print(weather)
weather[:, 1]

[[56 97 30]
 [58 86  6]
 [40 33 24]
 ...
 [47 40 29]
 [53 27 10]
 [13 46 50]]


array([97, 86, 33, 84, 14, 67, 68, 93,  3, 58, 93, 77, 81, 16, 62, 34, 32,
       17, 90, 64, 92, 51,  9, 68, 66, 14, 54,  0, 66, 44, 39, 96, 75, 82,
       12, 41, 32, 52, 82, 42,  1, 34, 70, 34, 74,  0, 11, 73, 15, 92, 50,
       74, 15, 24, 96, 50, 95, 92, 78, 46, 40, 56, 16, 97, 48, 77,  5, 37,
       53,  3, 11,  6, 55, 42, 29, 13, 64, 92, 68, 96, 81, 68,  6, 54, 99,
       84, 27, 25, 44, 83, 57, 24, 48, 21, 97, 54, 39, 80, 74, 71, 20, 96,
       49, 20, 40, 12, 46, 93,  4,  3, 84, 72, 66, 94,  2,  7, 69,  5, 59,
       84, 33, 48, 13, 46, 19, 44, 87, 80, 35, 27, 51, 99, 19, 76, 77, 11,
       31, 79, 97,  7, 90, 38, 57, 58, 93, 21, 64,  7,  1, 32, 84, 97, 82,
       54, 96, 99, 37, 80, 60, 22, 59, 83,  7, 73, 96, 66, 16, 60, 76, 61,
       22, 17, 88, 20, 20, 73, 10, 68,  2,  6, 69, 81, 22, 56, 71, 21, 21,
       97,  3, 71, 25, 88, 88, 67, 79, 78, 78, 76, 82, 10, 59, 82, 22, 21,
       80, 67, 27, 39, 47, 56, 91, 98, 62, 30, 30, 39, 37,  7, 22, 63, 68,
       70,  3, 89, 45, 58

## 8. Replace negative sensor readings with 0 using slicing.

In [25]:
sensor = np.array([12, -7, 5, 0, -3, 19, 8, -12, 4, 15])
sensor[sensor<0] = 0
sensor

array([12,  0,  5,  0,  0, 19,  8,  0,  4, 15])

## 9. Select middle 10% rows from a dataset

In [32]:
data = np.random.rand(100)
rows = data.shape[0]
half = 0.10 / 2
start = int(rows * (0.5 - half))
end   = int(rows * (0.5 + half))
data[start:end]

array([0.36117533, 0.35801072, 0.80965993, 0.43487277, 0.41296951,
       0.04030523, 0.36677043, 0.40995695, 0.56453028, 0.66153656])

## 10. Crop a 50x50 image to its center 20x20 reigon

In [49]:
img = np.arange(1, 2501).reshape(50, 50)
start = int((50-20)/2)
crop1 = img[start:, start:]
crop2 = crop1[:20, :20]
crop2

array([[ 766,  767,  768,  769,  770,  771,  772,  773,  774,  775,  776,
         777,  778,  779,  780,  781,  782,  783,  784,  785],
       [ 816,  817,  818,  819,  820,  821,  822,  823,  824,  825,  826,
         827,  828,  829,  830,  831,  832,  833,  834,  835],
       [ 866,  867,  868,  869,  870,  871,  872,  873,  874,  875,  876,
         877,  878,  879,  880,  881,  882,  883,  884,  885],
       [ 916,  917,  918,  919,  920,  921,  922,  923,  924,  925,  926,
         927,  928,  929,  930,  931,  932,  933,  934,  935],
       [ 966,  967,  968,  969,  970,  971,  972,  973,  974,  975,  976,
         977,  978,  979,  980,  981,  982,  983,  984,  985],
       [1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026,
        1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035],
       [1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076,
        1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085],
       [1116, 1117, 1118, 1119, 1120, 112